Fix getTimeIntervalStart() handling of daylight saving gaps
Replace `TimeIntervalType.clearField()` with `DateTimeFieldType.roundFloorCopy()`, since `clearField()` throws an exception if the time lies in a daylight-saving gap.

Several timezones have a daylight saving cutover of midnight: 00:00 becomes 01:00. The old implementation of `TimeIntervalType` truncated the time interval by setting each `subType` field to its minimum value. Unfortunately, if this time happened to correspond to a DST gap, then an `IllegalFieldValueException` exception would be thrown, e.g.:

    org.joda.time.IllegalFieldValueException: Value 0 for hourOfDay is not supported: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 2016-03-13T00:00:00.000 (America/Havana)